config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/show'
  #mount ActionCable.server => '/cable'

  get '/', to: 'static_pages#company', as: :top

  resources :mapus

get 'projects/marker',  to: 'projects#marker',  as: :marker  

  resources :tests

  get 'calendar/index'

    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/box'
  

resources :projects do
    resources :tasks, only: [:create, :destroy]
 end

 post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

 

config = Rails.application.config.taskapp







constraints host: config[:staff][:host] do
namespace :staff, path: config[:staff][:path] do
    root 'top#index'
    post ':id/toggle' => 'top#toggle'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new'
    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/forbidden'

    get 'static_pages/staff_flow'
    get 'static_pages/additional_info'
    get 'static_pages/sales_term'
    get 'static_pages/bank'
    get 'static_pages/funk1'
    get 'static_pages/funk2'
    get 'static_pages/funk3'
    get  'inquiry'         => 'inquiry#index'
    post 'inquiry/confirm' => 'inquiry#confirm'
    post 'inquiry/thanks'  => 'inquiry#thanks'

 
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create, :destroy ]
    resource :account, except: [ :new, :create ]
    resource :password, only: [ :show, :edit, :update ]
    
    resources :customers do
      member do
    get :following, :followers
    end
  end
    resources :staff_addresses
    resources :additional_infos
    resources :sales_terms
    resources :banks
    resources :schedules, only: [:create, :destroy ] do
      member do
      get :push
    end
    end
    resources :relationships, only: [:create, :destroy]
    resources :orders, only: [ :index, :show ] do
      get :shipped 
    end
    resources :prev_orders, only: [ :index, :show ] do
      get :shipped 
    end
    resources :tmbl_orders, only: [ :index, :show ] do
      get :shipped 
    end

    resources :products do
    get :who_bought, on: :member
    get :pg_new, on: :new
    get :pg_edit, on: :member
    end 
    
  end
end

constraints host: config[:admin][:host] do
namespace :admin, path: config[:admin][:path] do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new', as: :signup
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create ]
    resources :staff_members do
      resources :staff_events, only: [ :index ]

    end
    resources :staff_events, only: [ :index ] 
  end
end

constraints host: config[:special][:host] do
    namespace :special, path: config[:special][:path] do
        root 'top#index'
        
        resources :reservation 
        post 'reservation/box1' => 'reservation#box1'
        post 'reservation/box2' => 'reservation#box2'
        post 'reservation/box3' => 'reservation#box3'
        post 'reservation/confirm' => 'reservation#confirm'
        post 'reservation/thanks'  => 'reservation#thanks'
    end
end



constraints host: config[:customer][:host] do
namespace :customer, path: config[:customer][:path] do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new'
    get 'open_index' => 'staff_members#open_index'
    get 'search' => 'staff_members#search'
    get 'token/:uuid', :to => 'signups#token'
    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/forbidden'
    get 'static_pages/box'
    get 'static_pages/shizen'
    get 'static_pages/rule'
    get  'inquiry'         => 'inquiry#index'
    post 'inquiry/confirm' => 'inquiry#confirm'
    post 'inquiry/thanks'  => 'inquiry#thanks'
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create, :destroy ]

    resources :relationships, only: [ :create, :destroy ]
    resources :mypages
    resources :staff_members do
      member do
      get :following, :followers
      end
      get :sales_term
      get :schedules
      get :schedule_show
      resources :store, only: [ :index ]
      resources :product, only: [ :show ]
      resources :carts
      resources :line_items
      resources :orders 
      resources :addresses do
        member do
        post :order_conf
        get :thanks
        end
      end
    end
  end
end




  # priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root 'errors#routing_error'
  get '*anything' => 'errors#routing_error'
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
	skip_before_action :authorize

	def index
		if current_administrator
			render action: 'dashboard'
		else
			render action: 'index'
		end
	end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < Customer::Base
	  before_action :set_address, only: [:show, :edit, :update, :destroy]

	def index
		@customer = current_customer
		@addresses = @customer.addresses.all
		@addresses = @customer.addresses.page(params[:page])
	end 

	def order_conf
		@customer = current_customer
  		@staff_member_id = session[:order_staff]
  		@staff_member = StaffMember.find_by(id: @staff_member_id)
		cart = Cart.find_by(staff_member_id: @staff_member_id, customer_id: @customer.id)
		delivery_fee = @staff_member.sales_term.delivery_fee
		total_price = cart.total_price + delivery_fee
		if params[:name] == 'webpay'
            customer = Stripe::Customer.create(
                                               :email => params[:stripeEmail],
                                               :source  => params[:stripeToken] 
                                               )
  			charge = Stripe::Charge.create(
                                           :customer => customer.id,
                                           :currency => 'jpy',
                                           :amount => total_price,
                                           :description => 'Rails Stripe customer'
                                           )
  			@payment = "クレジット支払い"
  	    else
  	    	@payment = "代金引き換え"
  	    end
  	    
  		@address = Address.find(params[:id])	
  		@order = Order.new(
  			:staff_member_id => @staff_member_id, 
  			:customer_id => @customer.id, 
  			:total_price => total_price, 
  			:address_id => @address.id, 
  			:payment => @payment
  			)
  		@order.add_line_items_from_cart(cart)
  		address = @address
		

		respond_to do |format|
			if  @order.save!

		
				Cart.destroy(cart)
				

				OrderNotifier.received(@address, @payment, @order, @staff_member).deliver
				OrderNotifier.ordered(@address, @payment, @order, @staff_member).deliver
				
				format.html { redirect_to :thanks_customer_staff_member_address, notice: 'ご注文ありがとうございます' }
				format.json { render json: @address, status: :created, location: @address }
			else
				@cart = current_cart
				format.html { redirect_to :customer_root, notice: '注文に失敗しました。' }
				format.json { render json: @address.errors, status: :unprocessable_entity }
			end
		end

	end


	def show
		@customer = current_customer
  		@staff_member = StaffMember.find(params[:staff_member_id])
		@cart = Cart.find_by(staff_member_id: @staff_member.id, customer_id: @customer.id)
        @price = @cart.total_price
		@total_price = @cart.total_price + @staff_member.sales_term.delivery_fee
  		@address = Address.find(params[:id])
  		session[:order_staff] = @staff_member.id
  		@line_items = @cart.line_items
	end


	def edit
		@customer = current_customer
		@address = Address.find(params[:id])

	end

	def update
		@customer = current_customer
  		@staff_member = StaffMember.find(params[:staff_member_id])
  	    
  		@address = Address.find(params[:id])	
  		@address.assign_attributes(address_params) 
  		
		respond_to do |format|
			if @address.save!
							
				format.html { redirect_to :customer_staff_member_address, notice: '住所が選択されました。' }
				format.json { render json: @address, status: :created, location: @address }
			else
				@cart = current_cart
				format.html { render action: "new" }
				format.json { render json: @address.errors, status: :unprocessable_entity }
			end
		end
	end

	def new
		@customer = current_customer
  		@staff_member = StaffMember.find(params[:staff_member_id])
		@cart = Cart.find_by(staff_member_id: @staff_member.id, customer_id: @customer.id)
		if @cart.line_items.empty?
			redirect_to :customer_staff_member_store_index, notice: "カートは空です"
			return
		end
		@address = Address.new

		respond_to do |format|
		format.html 
		format.json { render json: @address }
		end
	end

	def create 
		@customer = current_customer
		@address = @customer.addresses.build(address_params)
  		address = @address

		respond_to do |format|
			if @address.save
				flash.notice = '新しい住所が登録されました。'
				format.html { redirect_to :customer_staff_member_addresses, notice: '新しい住所が登録されました。' }
				format.json { render json: @address, status: :created, location: @address }
			else
				@cart = current_cart
				format.html { render action: "new" }
				format.json { render json: @address.errors, status: :unprocessable_entity }
			end
		end
	end


	def destroy
		@customer = current_customer
		address = Address.find(params[:id])
		address.destroy!
		flash.notice = '選択された住所を削除しました。'
		redirect_to :customer_staff_member_addresses
	end


	 private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(
      	:postal_code, :prefecture, :city, :address1, :address2, :phone
      	) 
    end
    def phone_params(record_name)
	 	params.require(record_name).permit(phones: [ :number, :primary ])
	end
	def order_params
      params.require(:order).permit(
        :staff_member_id, :customer_id, :total_price, :address_id 
        ) 
    end
end

app/controllers/customer/base.rb
class Customer::Base < ApplicationController

	before_action :authorize

	before_action :check_timeout
	

	
	private
	def current_customer
		if session[:customer_id]
			@current_customer ||=
			Customer.find_by(id: session[:customer_id])
		end
	end

	helper_method :current_customer

	def authorize
		unless current_customer
			flash.alert = 'ログインして下さい。'
			redirect_to :customer_login
		end
	end



	TIMEOUT = 20.years

	def check_timeout
		if current_customer
			if session[:last_access_time] >= TIMEOUT.ago
				session[:last_access_time] = Time.current
			else
				session.delete(:customer_id)
				flash.alert = 'セッションがタイムアウトしました。'
				redirect_to :customer_login
			end
		end
	end
	


end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < Customer::Base
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @staff_member = StaffMember.find(params[:staff_member_id])
      customer = current_customer
   @cart = Cart.find!(["staff_member_id = ? and customer_id = ?", @staff_member.id, customer.id])
   
    rescue ActiveRecord::RecordNotFound
      logger.error "無効なカート#{params[:id]}にアクセスしようとしました"
      redirect_to store_url, notice: '無効なカートです'
    else
      respond_to do |format|
        format.html 
        format.json {render json: @cart }
      end 
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    staff_member = StaffMember.find(params[:id])
    cart = Cart.new(cart_params)

    respond_to do |format|
      if cart.save!
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy  
    @cart = Cart.find(params[:id])
    if params[:delete]
      @cart.line_items.each do |item|
        item.product.stock += 1
        item.product.save
      end
    end
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to :customer_staff_member_store_index }
      format.json { head :ok }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(
        :staff_member_id, :customer_id
        ) 
    end
end

app/controllers/customer/inquiry_controller.rb
class Customer::InquiryController  < Customer::Base
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      redirect_to :back
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    # send mail
    InquiryMailer.received_email(@inquiry).deliver

    flash[:notice] = "お問い合わせ頂き、ありがとうございました。"
    render :action => 'thanks'
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/controllers/customer/line_items_controller.rb
class Customer::LineItemsController < Customer::Base
	 before_action :set_line_item, only: [:show, :edit, :update, :destroy]

	def index
	end

	def show
	end

	def new
	end

	def edit
	end

	def create
		@cart = Cart.find(params[:cart_id]) 
		product = Product.find(params[:product_id])
			Product.decrease_stock(product)
			@line_item = @cart.add_product(product.id)
			respond_to do |format|
				if @line_item.save
					format.html { redirect_to :store_index }
					format.js { @current_item = @line_item }
					format.json { render json: @line_item,
						status: :created, location: @line_item }
				else
					format.html { render action: "new" }
					format.json { render json: @line_item.errors,
						status: :unprocessable_entity }
				end
	    	end
		
	end

	def update
	end

	def destroy
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params[:line_item]
    end
end

app/controllers/customer/mypages_controller.rb
class Customer::MypagesController < Customer::Base
    def index
		@customer = current_customer
	end   	


	def show
		@customer = current_customer
	end

	def following
		@title = "Following"
		@customer = current_customer
		@staff_members = @customer.followed_staff_members.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@customer = Customer.find(params[:id])
		@staff_members = @customer.followers.paginate(page: params[:page])
		render 'show_follow'
	end
end

app/views/customer/top/_cstats.html.erb
<div class="stats">
	<a href="<%= following_customer_staff_member_path(current_customer) %>">
	<strong id="followers" class="stat">
		 <%= current_customer.followed_staff_members.count %>
	</strong>
	following
	</a>
</div>
 

app/views/customer/top/_infowindow.html.erb
<h5><%= staff_member.staff_member.farm_name %></h5>
<h5>所在地:<%= staff_member.prefecture%> <%= staff_member.city %> <%= staff_member.address1 %> <%= staff_member.address2%></h5>
<% if staff_member.staff_member.additional_info %>
<h5>看板野菜:<%= staff_member.staff_member.additional_info.masterpiece %></h5>
<% end %>
<div class="pull-left"><div class="new-btn"><%= link_to 'どんな農家？', [:customer, staff_member.staff_member ], {:class => "btn" } %></div></div>
<div class="pull-left"><div class="new-btn"><%= link_to 'スケジュール', [:customer, staff_member.staff_member, :schedules], {:class => "btn" } %></div> </div>

app/views/customer/top/_member_header.html.erb
<div class="icon">
  <div class="follows">
    <%= render 'cstats' %>
  </div>
  <div class="cname">
    <%= current_customer.email %>
  </div>
</div>

app/views/customer/top/index.html.erb
  

 <div class="top-image">

  <%= render 'customer/shared/search_form' %>

</div>

<div class="insert">
  <div class="span12">
 <div id="tab">
<ul>
  <div class= "span3"><h5>　　</h5></div>
<div class= "span1"><li class="now"><h1><i class="ion-map"></i><h1><h5>地図で検索！</h5></li></div>
<div class= "span1"><li><h1><i class="ion-home"></i></h><h5>開店中のお店！</h5></li></div>
<div class= "span1"><li><h1><i class="ion-calendar"></i></h1><h5>農家のスケジュール！</h5></li></div>

</ul>
</div>
</div>

<div class="contents">
  <div class="map">
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map-canvas"></div>
</div>
</div>

<div class="contents">
 <div class="container">
    <div class="row">

      <div class="span12">
        <div class="events">
           <% if @open_staff_members.count == 0 %>
           <h4>ー現在購入できる農家さんはありませんー</h4>
           <h5>フォローして開店情報をいち早くGET！</h5>
           <%= link_to '登録農家を見てみる！', [:customer_staff_members ], {:class => "btn" } %>
            <% end %>
          <% @open_staff_members.each do |m| %>
            <div class="span3">
              <div class="bgc">
          <div class="events-area">
            <ul class="events-list">
              <li>
                <div class="event-box event-box-featured">
                  <% if m.image? %>
                  <div class="prof"><%= image_tag m.image.thumb.url %></div>
                  <% else %>
                  <div class="prof"><%= image_tag ("sample_img.png") %></div>
                  <% end %>
               
                  
                  
                  <div class="detail">
                    <h5><i class="ion-leaf"></i> <%= m.farm_name %></h5>
                  <h5><a href="<%= customer_staff_member_store_index_path(m) %>">OPEN!!</a></h5>
                  <% if m.staff_address %>
                  <h7><i class="ion-ios-location"></i> <%= m.staff_address.prefecture %> <%= m.staff_address.city %> <%= m.staff_address.address1 %> </h7>
                  <% end %>
                  <% if m.additional_info %>
                  <h6><i class="ion-heart"></i> 看板野菜：<%= m.additional_info.masterpiece %> </h6>
                  <% end %>
                    
                  
                          
                      <div class="new-btn"><%= link_to 'どんな農家？', [:customer, m ], {:class => "btn" } %>
                      
                        </div> 
                       
                        <div class="new-btn">
                      <%= link_to '商品を見る！', [:customer, m, :store, :index ], {:class => "btn btn-large btn-primary" } %>
                    </div>
                  </div>
                
                </div><!-- event-box ends -->
              </li>
            </ul>
    
          </div><!-- events-area ends -->
          </div>
        </div><!-- events end -->
   
      <% end %>

      </div>
      <div class="pull-left">
      <%= paginate @open_staff_members %>
    </div>
      </div>
     </div>
   </div>
 </div>
<div class="contents">  
<div class="container">    
  <div class="row">
      <div class="span12">
        <div class="events">
          
          <div class="widget">
           <% if @schedules.count == 0 %>
           <h4>ー現在表示できる投稿はありませんー</h4>
            <% end %>
                <% @schedules.each do |schedules| %>

           <li>
             <div class="event-box">
               <figure class="image">
                <%= image_tag schedules.staff_member.image.thumb.url %>
                 <a href="events-detail.html"></a>
               </figure>
             <div class="detail">
               <h5><a href="<%= customer_staff_member_schedules_path(schedules.staff_member) %>"><strong>【<%= schedules.staff_member.farm_name %>】<%= schedules.harvest %><%= schedules.opening %></strong> </a></h5>
                <ul>
                  <li><span><i class="ion-ios-clock"></i> <strong>開始日時：</strong><h3><strong>
                  <% if schedules.harvest_date? %>
                    <%= schedules.harvest_date.strftime("%Y年%m月%d日") %>
                    <% end %>
                    <% if schedules.opening_date? %>
                    <%= schedules.opening_date.strftime("%Y年%m月%d日 %H:%M") %><br>　　　　&#8659;<br><%= schedules.closing_date.strftime("%Y年%m月%d日 %H:%M") %>
                    <% end %></strong></h3></span></li>
                  <% if schedules.staff_member.additional_info %>
                  <li><i class="ion-information-circled"></i> 自然栽培<%= schedules.staff_member.additional_info.farm_condition_year %>|<%= schedules.staff_member.additional_info.farm_condition %></li>
                  <li><i class="ion-heart"></i> 看板やさい：<%= schedules.staff_member.additional_info.masterpiece %></li>
                  <% end %>
                    <% if schedules.staff_member.staff_address %>
                  <li><i class="ion-ios-location"></i> 
                    <%= schedules.staff_member.staff_address.prefecture %> 
                    <%= schedules.staff_member.staff_address.city %> 
                    <%= schedules.staff_member.staff_address.address1 %> </li>
                    <% end %>
                    <br/>
                    
                    <% if schedules.image1? %>
                    <div class="img">
                    <%= image_tag schedules.image1.url, :class => "intense" %>
                   </div>
                    
                    <% end %>
                    <% if schedules.image2? %>
                    <div class="img">
                    <%= image_tag schedules.image2.url, :class => "intense"  %>
                  </div>
                    <% end %>
                    <% if schedules.image3? %>
                    <div class="img">
                    <%= image_tag schedules.image3.url, :class => "intense"  %>
                  </div>
                    <% end %>
                  
              </ul>
             </div>
             </div><!-- event-box ends -->
           </li>
<% end %>
<%= paginate @schedules %>
              
           
          </div><!-- widget ends -->
                 
                    <h5>
                      <br/>
                      <%= link_to "→ごひいき農家予定一覧へ", customer_static_pages_feed_page_path, { :class => "btn"} %></h5>
                    
                  

                  
                </div><!-- event-box ends -->
              </div>
              </div>
            </div>
            </div>
<div class="contents">
  <div class="container">
  <div class="low">
          <div class="span12">


<br>



            <h2></h2>
  <ul class="bxslider1">
  <li><%= image_tag "flow_img.png" %></li>
  <li><%= image_tag "flow_img2.png" %></li>
  <li><%= image_tag "flow_img3.png" %></li>
</ul>
</div>
</div>
</div></div>
<div class="contents">ここに タブ03 がアクティブの時に表示する内容</div>
<div class="contents">ここに タブ04 がアクティブの時に表示する内容</div>
</div>


<div class="span4"><%= image_tag ("icon_sample3.png") %><br><h4>　
  地域の新規就農者の育成、地域の農を中心としたコミュニティーづくりに対して資金を提供する基金を創設します。</h4></div>
<div class="span4"><%= image_tag ("icon_sample1.png") %><br><h4>　
  地域の食糧自給の基盤となるシステムを提供します。皆様と生産者様が支え合い、助け合うことで生まれる、自立的な地域を作っていきます。
  </h4></div>
<div class="span4"><%= image_tag ("icon_sample2.png") %><br><h4>　生産者さんから売りたいタイミングでメッセージが届くので、何度もサイトを訪問しなくても、好きな地域の好きな生産者さんから購入できます。</h4></div>




  

          





          <script>
          $(document).ready(function(){
  $('.bxslider').bxSlider({
    auto: true,
    nextSelector: '#slider-next',
  prevSelector: '#slider-prev',
  pause: 6000,
  buildPager: function(slideIndex){
    switch(slideIndex){
      case 0:
        return '';
      case 1:
        return '';
      case 2:
        return '';
      case 3:
        return '';
      case 4:
        return '';
    }
  }
});
  });
          </script>

          <script>
          $(document).ready(function(){
  $('.bxslider1').bxSlider({
    auto: true,
    nextSelector: '#slider-next',
  prevSelector: '#slider-prev',
  pause: 6000,
  buildPager: function(slideIndex){
    switch(slideIndex){
      case 0:
        return '';
      case 1:
        return '';
      case 2:
        return '';
      case 3:
        return '';
      case 4:
        return '';
    }
  }
});
  });
          </script>

        
      
      

        
        

        
     
 
  

app/views/customer/top/show.html.erb
 <aside class="span4">
 <section>
        <%= render 'shared/stats' %>
 </section>
</aside>
<div class="span8">
	<%= render 'follow_form' if signed_in? %>
</div>

app/views/customer/top/show_following.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="span4">
		<section>
			<h2><%= @customer.email %></h2>
		</section>
		<section>
			<%= render 'stats' %>
			<% if @staff_members.any? %>
			<div class="staff_member_avatars">
				<% @staff_members.each do |staff_member| %>
				<%= staff_member.farm_name %>
				<% end %>
			</div>
			<% end %>
		</section>
	</aside>
	<div class="span8">
		<h3><%= @title %></h3>
		<% if @staff_members.any? %>
		<ul class="staff_members">
			<%= render @staff_members %>
		</ul>
		<%= will_paginate %>
		<% end %>
	</div>
</div>