config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/show'
  #mount ActionCable.server => '/cable'

  get '/', to: 'static_pages#company', as: :top

  resources :mapus

get 'projects/marker',  to: 'projects#marker',  as: :marker  

  resources :tests

  get 'calendar/index'

    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/box'
  

resources :projects do
    resources :tasks, only: [:create, :destroy]
 end

 post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

 

config = Rails.application.config.taskapp







constraints host: config[:staff][:host] do
namespace :staff, path: config[:staff][:path] do
    root 'top#index'
    post ':id/toggle' => 'top#toggle'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new'
    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/forbidden'

    get 'static_pages/staff_flow'
    get 'static_pages/additional_info'
    get 'static_pages/sales_term'
    get 'static_pages/bank'
    get 'static_pages/funk1'
    get 'static_pages/funk2'
    get 'static_pages/funk3'
    get  'inquiry'         => 'inquiry#index'
    post 'inquiry/confirm' => 'inquiry#confirm'
    post 'inquiry/thanks'  => 'inquiry#thanks'

 
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create, :destroy ]
    resource :account, except: [ :new, :create ]
    resource :password, only: [ :show, :edit, :update ]
    
    resources :customers do
      member do
    get :following, :followers
    end
  end
    resources :staff_addresses
    resources :additional_infos
    resources :sales_terms
    resources :banks
    resources :schedules, only: [:create, :destroy ] do
      member do
      get :push
    end
    end
    resources :relationships, only: [:create, :destroy]
    resources :orders, only: [ :index, :show ] do
      get :shipped 
    end
    resources :prev_orders, only: [ :index, :show ] do
      get :shipped 
    end
    resources :tmbl_orders, only: [ :index, :show ] do
      get :shipped 
    end

    resources :products do
    get :who_bought, on: :member
    get :pg_new, on: :new
    get :pg_edit, on: :member
    end 
    
  end
end

constraints host: config[:admin][:host] do
namespace :admin, path: config[:admin][:path] do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new', as: :signup
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create ]
    resources :staff_members do
      resources :staff_events, only: [ :index ]

    end
    resources :staff_events, only: [ :index ] 
  end
end

constraints host: config[:special][:host] do
    namespace :special, path: config[:special][:path] do
        root 'top#index'
        
        resources :reservation 
        post 'reservation/box1' => 'reservation#box1'
        post 'reservation/box2' => 'reservation#box2'
        post 'reservation/box3' => 'reservation#box3'
        post 'reservation/confirm' => 'reservation#confirm'
        post 'reservation/thanks'  => 'reservation#thanks'
    end
end



constraints host: config[:customer][:host] do
namespace :customer, path: config[:customer][:path] do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new'
    get 'open_index' => 'staff_members#open_index'
    get 'search' => 'staff_members#search'
    get 'token/:uuid', :to => 'signups#token'
    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/forbidden'
    get 'static_pages/box'
    get 'static_pages/shizen'
    get 'static_pages/rule'
    get  'inquiry'         => 'inquiry#index'
    post 'inquiry/confirm' => 'inquiry#confirm'
    post 'inquiry/thanks'  => 'inquiry#thanks'
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create, :destroy ]

    resources :relationships, only: [ :create, :destroy ]
    resources :mypages
    resources :staff_members do
      member do
      get :following, :followers
      end
      get :sales_term
      get :schedules
      get :schedule_show
      resources :store, only: [ :index ]
      resources :product, only: [ :show ]
      resources :carts
      resources :line_items
      resources :orders 
      resources :addresses do
        member do
        post :order_conf
        get :thanks
        end
      end
    end
  end
end




  # priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root 'errors#routing_error'
  get '*anything' => 'errors#routing_error'
end

app/controllers/staff/accounts_controller.rb
class Staff::AccountsController < Staff::Base
	def show
		@staff_member = current_staff_member
		
	end

	def edit
		@staff_member = current_staff_member
	end

	def schedule
		@staff_member = current_staff_member
	end

	def update
		@staff_member = current_staff_member
		@staff_member.assign_attributes(staff_member_params)
		
			if @staff_member.save
				flash.notice = 'アカウント情報を更新しました。'
				redirect_to :staff_account
			else
				render action: 'edit'
			end
		
	end

	private
	def staff_member_params
		params.require(:staff_member).permit(
			:farm_name, :email, :password, :family_name, :given_name,
			:family_name_kana, :given_name_kana,
			:suspended, :image, :image_cache, :remove_image, 
			:farmimg1, :farmimg2, :farmimg3, :farmimg1_cache, :farmimg2_cache, :farmimg3_cache, 
			:remove_farmimg1, :remove_farmimg2, :remove_farmimg3,
			:staff_address_attributes => [:postal_code, :prefecture, :city, :address1, :address2]
			)
	end
	
end

app/controllers/staff/additional_infos_controller.rb
class Staff::AdditionalInfosController < Staff::Base


	def index
		@staff_member = current_staff_member
		
	end

	def show
		@staff_member = current_staff_member
		@additional_infos = AdditionalInfo.find(params[:id])
	end

	def new
		@staff_member = current_staff_member
		@additional_infos = AdditionalInfo.new
	end

	def edit
		@staff_member = current_staff_member
		@additional_infos = @staff_member.additional_info
	end

	def create
		@staff_member = current_staff_member
		@additional_infos = @staff_member.build_additional_info(additional_info_params)
		
			if @additional_infos.save
				flash.notice = "販売条件を更新しました。"
				redirect_to :staff_root
			else
			render 'staff_root'
 	       end
	    
	end

	def update
    	@staff_member = current_staff_member
		@additional_infos = @staff_member.build_additional_info(additional_info_params)

    	if @additional_infos.save
				flash.notice = "追加情報を更新しました。"
				redirect_to :staff_root
			else
				flash.now.alert = '入力に誤りがあります。'
			render action: 'edit'
 	       end
    end



	def destroy
		@staff_member = current_staff_member
		@additional_infos = @staff_member.additional_infos.destroy!
		flash.notice = '販売条件を削除しました。'
		redirect_to :staff_roots
	end

	private


	def additional_info_params
		params.require(:additional_info).permit(:farm_condition, :farm_condition_year, :masterpiece, :explanation)
	end

end

app/controllers/staff/banks_controller.rb
class Staff::BanksController < Staff::Base

	def index
		@staff_member = current_staff_member
	end

	def new
		@staff_member = current_staff_member
		@bank = Bank.new
	end

	def show
		@staff_member = current_staff_member
		@bank = Bank.find(params[:id])
	end

	def edit
		@staff_member = current_staff_member
		@bank = @staff_member.bank
	end

	def create
		@staff_member = current_staff_member
		@bank = @staff_member.build_bank(bank_params)

		if @bank.save
			flash.notice = "売上振込先を更新しました。"
			redirect_to :staff_root
		else
			render 'staff_root'
		end
	end

	def update
		@staff_member = current_staff_member
		@bank = @staff_member.build_bank(bank_params)

		if @bank.save
			flash.notice = "売上振込先を更新しました。"
			redirect_to :staff_root
		else
			flash.now.alert = '入力に誤りがります。'
			render action: 'edit'
		end
	end

	private


	def bank_params
		params.require(:bank).permit(
			:bank_name, 
			:branch_name, 
			:account_type, 
			:account_number, 
			:account_holder
		)
	end
end

app/controllers/staff/base.rb
class Staff::Base < ApplicationController

	before_action :authorize
	
	before_action :check_timeout
	
	private
	def current_staff_member
		if session[:staff_member_id]
			@current_staff_member ||=
			StaffMember.find_by(id: session[:staff_member_id])
		end
	end

	helper_method :current_staff_member

	def authorize
		unless current_staff_member
			flash.alert = '販売者としてログインして下さい。'
			redirect_to :staff_login
		end
	end



	TIMEOUT = 1.years

	def check_timeout
		if current_staff_member
			if session[:last_access_time] >= TIMEOUT.ago
				session[:last_access_time] = Time.current
			else
				session.delete(:staff_member_id)
				flash.alert = 'セッションがタイムアウトしました。'
				redirect_to :staff_login
			end
		end
	end
	


end

app/controllers/staff/customers_controller.rb
class Staff::CustomersController < Staff::Base
	def index
		@search_form = Staff::CustomerSearchForm.new(params[:search])
		@customers = @search_form.search.page(params[:page])
	end

	def show
		@customer = Customer.find(params[:id])
		@staff_member = current_staff_member
		@order = Order.where(:staff_member_id => @staff_member.id, :customer_id => @customer.id)

	end

	def new
		@customer_form = Staff::CustomerForm.new
	end

	def edit
		@customer_form = Staff::CustomerForm.new(Customer.find(params[:id]))
	end

	def create
		@customer_form = Staff::CustomerForm.new
		@customer_form.assign_attributes(params[:form])
		if @customer_form.save
			flash.notice = '顧客を追加しました。'
			redirect_to action: 'index'
		else
			flash.now.alert = '入力に誤りがあります。'
			render action: 'new'
		end
	end

	def update
		@customer_form = Staff::CustomerForm.new(Customer.find(params[:id]))
		@customer_form.assign_attributes(params[:form])
		if @customer_form.save
			flash.notice = '顧客情報を更新しました。'
			redirect_to action: 'index'
		else
			flash.now.alert = '入力に誤りがあります。'
			render action: 'edit'
		end
	end

	def destroy
		customer = Customer.find(params[:id])
		customer.destroy!
		flash.notice = '顧客アカウントを削除しました。'
		redirect_to :staff_customers
	end

    def followers
    	@title = "Followers"
    	@staff_member = StaffMember.find(params[:id])
    	@customers = @staff_member.followers.all
    	render'show_follow'
    end

end

app/controllers/staff/events_controller.rb
class Staff::EventsController < Staff::Base
  before_action :set_event, only: [:show, :edit, :update, :destroy]


  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @staff_member = current_staff_member
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @staff_member = current_staff_member
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start, :end, :color, :allDay)
    end
end

app/controllers/staff/inquiry_controller.rb
class Staff::InquiryController  < Staff::Base
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    # send mail
    InquiryMailer.received_email(@inquiry).deliver

    flash[:notice] = "お問い合わせ頂き、ありがとうございました。"
    render :action => 'thanks'
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/controllers/staff/orders_controller.rb
class Staff::OrdersController < Staff::Base

	def index
		@staff_member = current_staff_member
		staff_member_id = @staff_member.id
		@credit_orders = Order.where(staff_member_id: @staff_member.id, created_at: Time.now.all_month, payment: "クレジット支払い")
		@money_orders = Order.where(staff_member_id: @staff_member.id, created_at: Time.now.all_month, payment: "代金引き換え")
		@orders = Order.where(staff_member_id: @staff_member.id, created_at: Time.now.all_month)
		@c_total_sales = @credit_orders.sum(:total_price)
		@m_total_sales = @money_orders.sum(:total_price)
		@total_sales = @orders.sum(:total_price)
		@month = Time.now.month
	end

	def prev_month
		prev = Time.now - 1.month

		@staff_member = current_staff_member
		staff_member_id = @staff_member.id
		@credit_orders = Order.where(staff_member_id: @staff_member.id, created_at: prev.all_month, payment: "クレジット支払い")
		@money_orders = Order.where(staff_member_id: @staff_member.id, created_at: prev.all_month, payment: "代金引き換え")
		@orders = Order.where(staff_member_id: @staff_member.id, created_at: prev.all_month)
		@c_total_sales = @credit_orders.sum(:total_price)
		@m_total_sales = @money_orders.sum(:total_price)
		@total_sales = @orders.sum(:total_price)
		@month = prev.month

	end

	def the_month_before_last
		tmbl = Time.now - 2.month
		@staff_member = current_staff_member
		staff_member_id = @staff_member.id
		@credit_orders = Order.where(staff_member_id: @staff_member.id, created_at: tmbl.all_month, payment: "クレジット支払い")
		@money_orders = Order.where(staff_member_id: @staff_member.id, created_at: tmbl.all_month, payment: "代金引き換え")
		@orders = Order.where(staff_member_id: @staff_member.id, created_at: tmbl.all_month)
		@c_total_sales = @credit_orders.sum(:total_price)
		@m_total_sales = @money_orders.sum(:total_price)
		@total_sales = @orders.sum(:total_price)
		@month = tmbl.month
	end


	def show
		@staff_member = current_staff_member
		@order = Order.find(params[:id])
		@address = Address.find_by(id: @order.address_id)

		respond_to do |format|
			format.html
			format.pdf do
				pdf = OrderPDF.new(@order, @address, @staff_member)
				pdf.font "vendor/fonts/ipaexg.ttf"

				send_data pdf.render,
				filename:  "#{@order.id}.pdf",
				type:      "application/pdf",
				disposition: "inline"
			end
		end

	end

	def new
	end

	def shipped

		@staff_member = current_staff_member
		@order = Order.find(params[:order_id])
		@customer = Customer.find_by(id: @order.customer_id)
		@address = Address.find_by(id: @order.address_id)
		@order.shipped = !@order.shipped
		@order.save
		OrderNotifier.shipped(@staff_member, @address, @order, @customer).deliver
		flash.notice = '発送通知が完了しました。'
		redirect_to :action => 'index'
	end
end

app/views/staff/tmbl_orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="top-nav">
      <div class="pull-left">
      <%= link_to '先月 >', [:staff_prev_orders], :class => "btn btn-primary" %>
       <%= link_to '当月 >', [:staff_orders], :class => "btn btn-primary" %>
       </div>
 <div class="l-box-lrg pure-u-1 pure-u-md-1"><h1><%= @month %>月度の総売上　¥<%= @total_sales %>-</h1></div>

</div>

</br>


<div class="l-box-lrg pure-u-1 pure-u-md-2-5">
   <div class="pull-left">
  <h3><i class="ion-social-yen"></i>　代金引き換え</h3>
</div>
  <table class="table">

  <tr>
  <th>売上</th>　
  <td>¥<%= @m_total_sales %></td>
</tr>

 <tr>
  <th>システム料</br>(売上の10％)</th>
  <td>¥<%= @m_total_sales * 0.1 %></td>
</tr>
 <tr>
  <th>合計</th>　
  <td>¥<%= @m_total_sales * 0.9 %></td>
</tr>
</table>
</div>

<div class="l-box-lrg pure-u-1 pure-u-md-2-5">
   <div class="pull-left">
  <h3><i class="ion-card"></i>　クレジット支払い</h3>
</div>
  <table class="table">

  <tr>
  <th>売上</th>　
  <td>¥<%= @c_total_sales %></td>
</tr>
 <tr>
  <th>システム料</br>(売上の10％)</th>　
  <td>¥<%= @c_total_sales * 0.1 %></td>
</tr>
 <tr>
  <th>合計</th>　
  <td>¥<%= @c_total_sales * 0.9 %></td>
</tr>
</table>
</div>

<div class="l-box-lrg pure-u-1 pure-u-md-1">
  <div class="pull-right">
<table class="table">
<tr>
  <th><h4>　<%= @month %>月度 お振込金額：</h4></th>　
  <td><h4>¥ <%= @c_total_sales * 0.9 - @m_total_sales * 0.1 %></h4></td>
</tr>

<tr>
  <th>※マイナスの表示はご請求金額</th>　
  <td></td>
</tr>

</table>
</div>
  </div>

<div class="l-box-lrg pure-u-1 pure-u-md-1">
  <h3><i class="ion-stats-bars"></i>　注文履歴</h3>
  <h5>決済日から3日以内に商品の発送を完了し、「発送完了メール送信」ボタンを押してください。<br/>ボタンを押すと、発送完了のメールが、自動的にお客様に届きます。※一度押してしまうとキャンセルはできませんのでご注意下さい。</h5></div>
<table class="table">
    <tr>
      <th>ステータス</th>
      <th>支払い方法</th>
      <th>名前</th>
      <th>決済金額(送料込)</th>
      <th>決済日時</th>
      <th>注文内容</th>
      <th colspan="3"></th>
    </tr>
 <% if @orders.count == 0 %>
<h4>ー現在表示できる売上がありませんー</h4>
<% end %>

  
    <% @orders.each do |order| %>
      <tr>
        <% if order.shipped == false %>
        <td><h3><%= link_to '発送完了メール送信', [:staff, order, :shipped], { :data => {:confirm => "発送完了の通知を送信しますか?"}, :class => "btn btn-yellow" } %> </h3></td>
        <% else %>
        <td>発送通知完了</td>
        <% end %>
        <td><%= order.payment %></td>
        <td><%= order.customer.family_name %> <%= order.customer.given_name %></td>

        <td>¥<%= order.total_price %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to '詳細確認＞', [:staff, order] , :class => "btn btn-dark"%></td>
        <td>  </td>
      </tr>
    <% end %>

</table>

</div>





<br>
</div>
</div>
</div>

app/views/staff/tmbl_orders/shipped.html.erb
<div class="container">
  <div class="row">
    <div class="span12">

<div><h3>発送完了通知が送信されました。ご対応いただき、誠にありがとうございます！</h3>
	<h6>　<strong>【 <%= @order.created_at %> 】</strong>注文分の商品発送が完了した旨、通知いたしました。<br/>　伝達事項などございましたら、以下記載のメールアドレスへ、直接ご連絡ください。</h6><br/>
	<h5>　　連絡先：<%= @order.customer.email %>
	<h5>購入者氏名：<%= @order.customer.family_name %> <%= @order.customer.given_name %>様</h5>
	<h5>送り先住所：〒<%= @address.postal_code %> <%= @address.prefecture %> <%= @address.city %> <%= @address.address1 %> <%= @address.address2 %></h5></div>
	<h5>通知完了時刻：<%= Time.now %></h5>



<br>


<%= link_to 'Home', :staff_root %>
</div>
</div>
</div>

app/views/staff/tmbl_orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">

<div>
<h3>受注票</h3><br/>
<h5>　<strong>　注文日時：<%= @order.created_at %></strong></h5>
<h5>　　　注文者：<%= @order.customer.family_name %> <%= @order.customer.given_name %>様</h5>
<h5>　　　連絡先：<%= @order.customer.email %></h5>
<h5>　送り先住所：〒<%= @address.postal_code %> <%= @address.prefecture %> <%= @address.city %> <%= @address.address1 %> <%= @address.address2 %></h5>
<h5>　　電話番号：<%= @address.phone %></h5>
<h5>お支払い方法：<%= @order.payment %></h5></div>
</div>
</div>
</div><br><br><br>
<div class="container">
  <div class="row">
  	<div class="span3">
<table class="table">
	<tr>
<th>一律送料：  ¥<%= @staff_member.sales_term.delivery_fee %></th><td></td>
		</tr>
	</table>
</div>
    <div class="span12">
<table class="table">	
 <tr>
      <th>品目</th>
      <th>品種</th>
      <th>内容量</th>
      <th>注文数</th>
      <th>小計</th>
      
    </tr>

<%= render @order.line_items %>
	
</table>


<div class="pull-right"><h3>合計： ¥<%= @order.total_price %>-（税込）</h3></div>
<br>
<%= link_to "受注票をダウンロード(PDF形式)", staff_order_path(@order, format: "pdf"), :class => 'btn' %>
<!-- Twitter -->


</div>
</div>
</div>