config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/show'
  #mount ActionCable.server => '/cable'

  get '/', to: 'static_pages#company', as: :top

  resources :mapus

get 'projects/marker',  to: 'projects#marker',  as: :marker  

  resources :tests

  get 'calendar/index'

    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/box'
  

resources :projects do
    resources :tasks, only: [:create, :destroy]
 end

 post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

 

config = Rails.application.config.taskapp







constraints host: config[:staff][:host] do
namespace :staff, path: config[:staff][:path] do
    root 'top#index'
    post ':id/toggle' => 'top#toggle'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new'
    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/forbidden'

    get 'static_pages/staff_flow'
    get 'static_pages/additional_info'
    get 'static_pages/sales_term'
    get 'static_pages/bank'
    get 'static_pages/funk1'
    get 'static_pages/funk2'
    get 'static_pages/funk3'
    get  'inquiry'         => 'inquiry#index'
    post 'inquiry/confirm' => 'inquiry#confirm'
    post 'inquiry/thanks'  => 'inquiry#thanks'

 
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create, :destroy ]
    resource :account, except: [ :new, :create ]
    resource :password, only: [ :show, :edit, :update ]
    
    resources :customers do
      member do
    get :following, :followers
    end
  end
    resources :staff_addresses
    resources :additional_infos
    resources :sales_terms
    resources :banks
    resources :schedules, only: [:create, :destroy ] do
      member do
      get :push
    end
    end
    resources :relationships, only: [:create, :destroy]
    resources :orders, only: [ :index, :show ] do
      get :shipped 
    end
    resources :prev_orders, only: [ :index, :show ] do
      get :shipped 
    end
    resources :tmbl_orders, only: [ :index, :show ] do
      get :shipped 
    end

    resources :products do
    get :who_bought, on: :member
    get :pg_new, on: :new
    get :pg_edit, on: :member
    end 
    
  end
end

constraints host: config[:admin][:host] do
namespace :admin, path: config[:admin][:path] do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new', as: :signup
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create ]
    resources :staff_members do
      resources :staff_events, only: [ :index ]

    end
    resources :staff_events, only: [ :index ] 
  end
end

constraints host: config[:special][:host] do
    namespace :special, path: config[:special][:path] do
        root 'top#index'
        
        resources :reservation 
        post 'reservation/box1' => 'reservation#box1'
        post 'reservation/box2' => 'reservation#box2'
        post 'reservation/box3' => 'reservation#box3'
        post 'reservation/confirm' => 'reservation#confirm'
        post 'reservation/thanks'  => 'reservation#thanks'
    end
end



constraints host: config[:customer][:host] do
namespace :customer, path: config[:customer][:path] do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    get 'signup' => 'signups#new'
    get 'open_index' => 'staff_members#open_index'
    get 'search' => 'staff_members#search'
    get 'token/:uuid', :to => 'signups#token'
    get 'static_pages/company'
    get 'static_pages/feed_page'
    get 'static_pages/intro'
    get 'static_pages/qa'
    get 'static_pages/commercial_transaction'
    get 'static_pages/policy'
    get 'static_pages/disclaimer'
    get 'static_pages/term'
    get 'static_pages/forbidden'
    get 'static_pages/box'
    get 'static_pages/shizen'
    get 'static_pages/rule'
    get  'inquiry'         => 'inquiry#index'
    post 'inquiry/confirm' => 'inquiry#confirm'
    post 'inquiry/thanks'  => 'inquiry#thanks'
    resource :session, only: [ :create, :destroy ]
    resource :signup, only: [ :create, :destroy ]

    resources :relationships, only: [ :create, :destroy ]
    resources :mypages
    resources :staff_members do
      member do
      get :following, :followers
      end
      get :sales_term
      get :schedules
      get :schedule_show
      resources :store, only: [ :index ]
      resources :product, only: [ :show ]
      resources :carts
      resources :line_items
      resources :orders 
      resources :addresses do
        member do
        post :order_conf
        get :thanks
        end
      end
    end
  end
end




  # priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root 'errors#routing_error'
  get '*anything' => 'errors#routing_error'
end

app/controllers/admin/staff_members_controller.rb
class Admin::StaffMembersController < Admin::Base

	before_action :authorize

	def index
		@staff_members = StaffMember.order(:family_name_kana, :given_name_kana)
		@staff_members = @staff_members.page(params[:page]) 
	end

	def show
		staff_member = StaffMember.find(params[:id])
		redirect_to [ :edit, :admin, staff_member ]
	end

	def new
		@staff_member = StaffMember.new
	end

	def edit
		@staff_member = StaffMember.find(params[:id])
	end

	def create
		@staff_member = StaffMember.new(staff_member_params)
		if @staff_member.save
			flash.notice = '販売アカウントを新規登録しました。'
			redirect_to :admin_staff_members
		else
			render action: 'new'
		end
	end

	def update
		@staff_member = StaffMember.find(params[:id])
		@staff_member.assign_attributes(staff_member_params)
		if @staff_member.save
			flash.notice = '販売アカウントを更新しました。'
			redirect_to :admin_staff_members
		else
			render action: 'edit'
		end
	end

	def destroy
		staff_member = StaffMember.find(params[:id])
		staff_member.destroy!
		flash.notice = '販売アカウントを削除しました。'
		redirect_to :admin_staff_members
	end

	private

	def authorize
		unless current_administrator
			flash.alert = '管理者としてログインして下さい。'
			redirect_to :admin_login
		end
	end

	def staff_member_params
		params.require(:staff_member).permit(
			:farm_name, :email, :password, :family_name, :given_name,
			:family_name_kana, :given_name_kana,
			:start_date, :end_date, :suspended, :name, 
			:description, :image
			)
	end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < Customer::Base
	  before_action :set_address, only: [:show, :edit, :update, :destroy]

	def index
		@customer = current_customer
		@addresses = @customer.addresses.all
		@addresses = @customer.addresses.page(params[:page])
	end 

	def order_conf
		@customer = current_customer
  		@staff_member_id = session[:order_staff]
  		@staff_member = StaffMember.find_by(id: @staff_member_id)
		cart = Cart.find_by(staff_member_id: @staff_member_id, customer_id: @customer.id)
		delivery_fee = @staff_member.sales_term.delivery_fee
		total_price = cart.total_price + delivery_fee
		if params[:name] == 'webpay'
            customer = Stripe::Customer.create(
                                               :email => params[:stripeEmail],
                                               :source  => params[:stripeToken] 
                                               )
  			charge = Stripe::Charge.create(
                                           :customer => customer.id,
                                           :currency => 'jpy',
                                           :amount => total_price,
                                           :description => 'Rails Stripe customer'
                                           )
  			@payment = "クレジット支払い"
  	    else
  	    	@payment = "代金引き換え"
  	    end
  	    
  		@address = Address.find(params[:id])	
  		@order = Order.new(
  			:staff_member_id => @staff_member_id, 
  			:customer_id => @customer.id, 
  			:total_price => total_price, 
  			:address_id => @address.id, 
  			:payment => @payment
  			)
  		@order.add_line_items_from_cart(cart)
  		address = @address
		

		respond_to do |format|
			if  @order.save!

		
				Cart.destroy(cart)
				

				OrderNotifier.received(@address, @payment, @order, @staff_member).deliver
				OrderNotifier.ordered(@address, @payment, @order, @staff_member).deliver
				
				format.html { redirect_to :thanks_customer_staff_member_address, notice: 'ご注文ありがとうございます' }
				format.json { render json: @address, status: :created, location: @address }
			else
				@cart = current_cart
				format.html { redirect_to :customer_root, notice: '注文に失敗しました。' }
				format.json { render json: @address.errors, status: :unprocessable_entity }
			end
		end

	end


	def show
		@customer = current_customer
  		@staff_member = StaffMember.find(params[:staff_member_id])
		@cart = Cart.find_by(staff_member_id: @staff_member.id, customer_id: @customer.id)
        @price = @cart.total_price
		@total_price = @cart.total_price + @staff_member.sales_term.delivery_fee
  		@address = Address.find(params[:id])
  		session[:order_staff] = @staff_member.id
  		@line_items = @cart.line_items
	end


	def edit
		@customer = current_customer
		@address = Address.find(params[:id])

	end

	def update
		@customer = current_customer
  		@staff_member = StaffMember.find(params[:staff_member_id])
  	    
  		@address = Address.find(params[:id])	
  		@address.assign_attributes(address_params) 
  		
		respond_to do |format|
			if @address.save!
							
				format.html { redirect_to :customer_staff_member_address, notice: '住所が選択されました。' }
				format.json { render json: @address, status: :created, location: @address }
			else
				@cart = current_cart
				format.html { render action: "new" }
				format.json { render json: @address.errors, status: :unprocessable_entity }
			end
		end
	end

	def new
		@customer = current_customer
  		@staff_member = StaffMember.find(params[:staff_member_id])
		@cart = Cart.find_by(staff_member_id: @staff_member.id, customer_id: @customer.id)
		if @cart.line_items.empty?
			redirect_to :customer_staff_member_store_index, notice: "カートは空です"
			return
		end
		@address = Address.new

		respond_to do |format|
		format.html 
		format.json { render json: @address }
		end
	end

	def create 
		@customer = current_customer
		@address = @customer.addresses.build(address_params)
  		address = @address

		respond_to do |format|
			if @address.save
				flash.notice = '新しい住所が登録されました。'
				format.html { redirect_to :customer_staff_member_addresses, notice: '新しい住所が登録されました。' }
				format.json { render json: @address, status: :created, location: @address }
			else
				@cart = current_cart
				format.html { render action: "new" }
				format.json { render json: @address.errors, status: :unprocessable_entity }
			end
		end
	end


	def destroy
		@customer = current_customer
		address = Address.find(params[:id])
		address.destroy!
		flash.notice = '選択された住所を削除しました。'
		redirect_to :customer_staff_member_addresses
	end


	 private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(
      	:postal_code, :prefecture, :city, :address1, :address2, :phone
      	) 
    end
    def phone_params(record_name)
	 	params.require(record_name).permit(phones: [ :number, :primary ])
	end
	def order_params
      params.require(:order).permit(
        :staff_member_id, :customer_id, :total_price, :address_id 
        ) 
    end
end

app/controllers/customer/base.rb
class Customer::Base < ApplicationController

	before_action :authorize

	before_action :check_timeout
	

	
	private
	def current_customer
		if session[:customer_id]
			@current_customer ||=
			Customer.find_by(id: session[:customer_id])
		end
	end

	helper_method :current_customer

	def authorize
		unless current_customer
			flash.alert = 'ログインして下さい。'
			redirect_to :customer_login
		end
	end



	TIMEOUT = 20.years

	def check_timeout
		if current_customer
			if session[:last_access_time] >= TIMEOUT.ago
				session[:last_access_time] = Time.current
			else
				session.delete(:customer_id)
				flash.alert = 'セッションがタイムアウトしました。'
				redirect_to :customer_login
			end
		end
	end
	


end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < Customer::Base
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @staff_member = StaffMember.find(params[:staff_member_id])
      customer = current_customer
   @cart = Cart.find!(["staff_member_id = ? and customer_id = ?", @staff_member.id, customer.id])
   
    rescue ActiveRecord::RecordNotFound
      logger.error "無効なカート#{params[:id]}にアクセスしようとしました"
      redirect_to store_url, notice: '無効なカートです'
    else
      respond_to do |format|
        format.html 
        format.json {render json: @cart }
      end 
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    staff_member = StaffMember.find(params[:id])
    cart = Cart.new(cart_params)

    respond_to do |format|
      if cart.save!
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy  
    @cart = Cart.find(params[:id])
    if params[:delete]
      @cart.line_items.each do |item|
        item.product.stock += 1
        item.product.save
      end
    end
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to :customer_staff_member_store_index }
      format.json { head :ok }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(
        :staff_member_id, :customer_id
        ) 
    end
end

app/controllers/customer/inquiry_controller.rb
class Customer::InquiryController  < Customer::Base
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      redirect_to :back
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    # send mail
    InquiryMailer.received_email(@inquiry).deliver

    flash[:notice] = "お問い合わせ頂き、ありがとうございました。"
    render :action => 'thanks'
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < Customer::Base

	def create
		@staff_member = StaffMember.find(params[:relationship][:followed_id])
		current_customer.follow!(@staff_member)
		redirect_to (:back)
	end

	def destroy
		@staff_member = Relationship.find(params[:id]).followed
		current_customer.unfollow!(@staff_member)
		redirect_to (:back)
	end
end

app/helpers/admin/staff_member_helper.rb
module Admin::StaffMemberHelper
end

app/views/customer/staff_members/_follow.html.erb
<%= form_for [:customer, @customer.relationships.build(followed_id: @staff_member.id)] do |f| %>
<div><%= f.hidden_field :followed_id %></div>
<%= f.submit "この農家をフォローする", :class => "pure-button pure-button-primary"%>
<% end %>

app/views/customer/staff_members/_stats.html.erb
	  	<p>

		 <%= @staff_member.followers.count %>

	followers
      </p>

app/views/customer/staff_members/_unfollow.html.erb
<%= form_for([ :customer, @customer.relationships.find_by(followed_id: @staff_member.id)], html: { method: :delete }) do |f| %>
<%= f.submit "フォローを解除", :class => "pure-button pure-button-primary"%>
<% end %>

app/views/customer/staff_members/index.html.erb
<div class="container">
    <div class="row">
<div class="span12">
      <% @title = '販売者一覧' %>
			<h2><%= @title %></h2>
		</div>
       
        <div class="events">
        	<%= paginate @staff_members %>
          <% @staff_members.each do |m| %>
          <% p = StaffMemberPresenter.new(m, self) %>
            <div class="span3">
              <div class="bgc">
          <div class="events-area">
            <ul class="events-list">
              <li>
                <div class="event-box event-box-featured">
                  <% if m.image? %>
                  <div class="prof"><%= image_tag m.image.thumb.url %></div>
                  <% else %>
                  <div class="prof"><%= image_tag ("sample_img.png") %></div>
                  <% end %>
               
                  
                  
                  <div class="detail">
                    <h5><i class="ion-leaf"></i> <%= m.farm_name %></h5>
                  <h5><a href="<%= customer_staff_member_store_index_path(m) %>"><%= p.suspended_mark %></a></h5>
                  <ul>
                  <% if m.staff_address %>
                  <li><i class="ion-ios-location"></i> <%= m.staff_address.prefecture %> <%= m.staff_address.city %> <%= m.staff_address.address1 %> </li><br>
                  <% else %>
                  <li><i class="ion-ios-location"></i> 未登録</li><br>
                  <% end %>
                  <% if m.additional_info %>
                  <li><i class="ion-heart"></i> 看板野菜：<%= m.additional_info.masterpiece %> </li>
                  <% else %>
                  <li><i class="ion-heart"></i> 看板野菜：未登録 </li>
                  <% end %>
                    </ul>
                  
                          
                      <div class="new-btn"><%= link_to 'どんな農家？', [:customer, m ], {:class => "btn" } %>
                      
                        </div> 
                       
                        <div class="new-btn">
                      <%= link_to '商品を見る！', [:customer, m, :store, :index ], {:class => "btn btn-large btn-primary" } %>
                    </div>
                  </div>
                
                </div><!-- event-box ends -->
              </li>
            </ul>
    
          </div><!-- events-area ends -->
          </div>
        </div><!-- events end -->
   
      <% end %>

      </div>
      <div class="pull-left">
      <%= paginate @staff_members %>
    </div>
      </div>
     </div>
  

app/views/customer/staff_members/sales_term.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			
			<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<% @title = '特定商取引に関する表示' %>
				<h2 class="text-pink">
					<%= @title %>
				</h2>

	</div>
</div>

</div>


<div class="container">
	<div class="row">
		<div class="span12">


		<h4><strong><%= simple_format @staff_member.sales_term.legal_info %></strong></h4>
		
	<%= link_to 'お店に戻る＞', [:customer_staff_member_store_index], {:class => "btn btn-large btn-primary" } %>

	</div>
</div>
</div>

app/views/customer/staff_members/schedule_show.html.erb
     

<div class="margin15">

<%= link_to "ホーム", :customer_root %> > <%= link_to "ブログ・投稿一覧", :customer_staff_member_schedules %> > ブログ詳細 </div>


<div id="layout" class="pure-g">
   

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            <!-- A wrapper for all the blog posts -->
            
<div class="margin15">
            <div class="posts">
                <h1 class="content-subhead">Selected Post</h1>

                <section class="post">
                    <header class="post-header">
                    

                        <h2 class="post-title"><%= truncate(@schedule.harvest, length: 15) %><%= truncate(@schedule.title, length: 15) %></h2>

                        <p class="post-meta">
                            By <a href="<%= customer_staff_member_schedules_path(@schedule.staff_member) %>", class="post-auther"><%= @schedule.staff_member.farm_name %></a> under 
                            <% if @schedule.harvest %>
                            <a class="post-category post-category-design" href="#">収穫予告</a>
                            <% else %>
                            <a class="post-category post-category-js" href="#">Blog</a>
                            <% end %><br>
<%= link_to 'http://www.facebook.com/sharer.php?u='+customer_staff_member_schedule_show_url(:staff_member_id => @staff_member, :schedule_id => @schedule.id ), :target => :blank do %> <%= image_tag 'FB.png' , :width => "20px" %>share<% end %>

                        </p>
                    </header>

                    <div class="post-description">


                        <p class="schedule-meta">
                        <%== @schedule.harvest %><%== @schedule.blog %>
                        </p>

                            <div class="post-images pure-g">
                            <div class="pure-u-1 pure-u-md-1-2">
                                <% if @schedule.image1? %>
                                <%= image_tag @schedule.image1.url, :class => "pure-img-responsive" %>
                                <% end %>


                                <!--<div class="post-image-meta">
                                    <h3>CSSConf Photos</h3>
                                </div>-->
                            </div>
                            <div class="pure-u-1 pure-u-md-1-2">
                                <% if @schedule.image2? %>
                                <%= image_tag @schedule.image2.url, :class => "pure-img-responsive" %>
                                <% end %>


                                <!--<div class="post-image-meta">
                                    <h3>CSSConf Photos</h3>
                                </div>-->
                            </div>

                        </div>
                    </div>
                </section>
            </div>
        </div>

        </div>
    </div>

   <div class="pure-u-1 pure-u-md-1-4">

<div class="margin15">
        <div class="header content">
        <% if @staff_member.image? %>
        <%= image_tag @staff_member.image.thumb.url, :size => "48x48", :class => "post-avatar" %>
        <% end %>
            <h1 class="brand-title"><%= @staff_member.farm_name %></h1>
            <h2 class="brand-tagline">ブログ</h2>

            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <%= link_to "当農園詳細はこちら", customer_staff_member_path(@staff_member), { :class => "pure-button"} %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "農産品はこちら", customer_staff_member_store_index_path(@staff_member), { :class => "pure-button"} %>
                    </li>
                </ul>
            </nav>
        </div>

    </div>


<div class="margin15">
          <div class="posts content">
                <h1 class="content-subhead">Recent Posts</h1>
            <% @schedules.each do |schedules| %>
                <section class="post">
                    <header class="post-header">
                    <% if @staff_member.image? %>
                    <%= image_tag schedules.staff_member.image.thumb.url, :size => "48x48", :class => "post-avatar" %>
                        <% end %>

                        <p><%= link_to customer_staff_member_schedule_show_path( schedule_id: schedules.id ) do %><%= truncate(schedules.harvest, length: 15) %><%= truncate(schedules.title, length: 15) %><% end %></p>
                         <%= link_to '...続きを読む', customer_staff_member_schedule_show_path( schedule_id: schedules.id ) %>


                        <p class="post-meta">
                            By <a href="<%= customer_staff_member_schedules_path(schedules.staff_member) %>", class="post-auther"><%= schedules.staff_member.farm_name %></a> under 
                            <% if schedules.harvest %>
                            <a class="post-category post-category-design" href="#">収穫予告</a>
                            <% else %>
                            <a class="post-category post-category-js" href="#">Blog</a>
                            <% end %>
                        </p>
                    </header>
                </section>
             <% end %>
            </div>

        </div>


    </div>
</div>

app/views/customer/staff_members/schedules.html.erb
     
<div class="margin15">

<%= link_to "ホーム", :customer_root %> > ブログ・投稿一覧  </div>

<div id="layout" class="pure-g">
   

    <div class="content pure-u-1 pure-u-md-3-4">
<div class="margin15">
            <!-- A wrapper for all the blog posts -->
            <% if @schedules.count == 0 %>

            <div class="posts">
                <h1 class="content-subhead">Pinned Post</h1>

                <!-- A single blog post -->
                <section class="post">
                    <h4>ー現在表示できる投稿はありませんー</h4>
                </section>
            </div>

            <% end %>


            <div class="posts">
                <h1 class="content-subhead">Recent Posts</h1>

<% @schedules.each do |schedules| %>
                <section class="post">
                    <header class="post-header">

                    <!--<% if schedules.staff_member.image? %><%= image_tag schedules.staff_member.image.thumb.url, :size => "48x48", :class => "post-avatar" %>
                        <img width="48" height="48" alt="Eric Ferraiuolo&#x27;s avatar" class="post-avatar" src="img/common/ericf-avatar.png"><% end %>-->

                        <h2 class="post-title"><%= link_to customer_staff_member_schedule_show_path( schedule_id: schedules.id ) do %><%= truncate(schedules.harvest, length: 15) %><%= truncate(schedules.title, length: 15) %><% end %></h2>

                        <p class="post-meta">
                            By <a href="<%= customer_staff_member_schedules_path(schedules.staff_member) %>", class="post-auther"><%= schedules.staff_member.farm_name %></a> under 
                            <% if schedules.harvest %>
                            <a class="post-category post-category-design" href="#">収穫予告</a>
                            <% else %>
                            <a class="post-category post-category-js" href="#">Blog</a>
                            <% end %>
                        </p>
                    </header>

                    <div class="post-description">


                        <p class="schedule-meta">
                        <%== schedules.harvest %><%== schedules.blog %>
                        </p>
                        <%= link_to '...続きを読む', customer_staff_member_schedule_show_path( schedule_id: schedules.id ) %>

                            <div class="post-images pure-g">
                            <div class="pure-u-1 pure-u-md-1-2">
                                <% if schedules.image1? %>
                                <%= image_tag schedules.image1.url, :class => "pure-img-responsive" %>
                                <% end %>


                                <!--<div class="post-image-meta">
                                    <h3>CSSConf Photos</h3>
                                </div>-->
                            </div>


                                <!--<div class="post-image-meta">
                                    <h3>CSSConf Photos</h3>
                                </div>-->

                            </div>
                            </div>
                </section>
                <h1 class="content-subhead"></h1>
                <% end %>
                </div>
            </div>


            </div>


   <div class="pure-u-1 pure-u-md-1-4">
   <div class="margin15">
        <div class="header">
        <% if @staff_member.image? %>
        <%= image_tag @staff_member.image.thumb.url, :size => "48x48", :class => "post-avatar" %><% end %>
            <h1 class="brand-title"><%= @staff_member.farm_name %></h1>
            <h2 class="brand-tagline">ブログ</h2>

            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <%= link_to "この農家の詳細を見にいく", customer_staff_member_path(@staff_member), { :class => "pure-button"} %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "農産品を見にいく", customer_staff_member_store_index_path(@staff_member), { :class => "pure-button"} %>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    </div>
</div>